name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [zstd, aria2, lshw, socat, sockperf, iperf]

    steps:
      - uses: actions/checkout@v3
      - name: build.sh
        run: ./build.sh ${{ matrix.repo }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BIN_BUILD: Y
      - uses: gautamkrishnar/keepalive-workflow@v1
  pack-x64:
    needs: build-x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run.sh
        run: ./run.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: gautamkrishnar/keepalive-workflow@v1
  pack-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apt
        run: |
          sudo apt update -y
          sudo apt install -y qemu-user-static
      - name: run.sh
        run: ./run.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ARCH: aarch64
  keepalive:
    needs: [build-x64, pack-x64, pack-aarch64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
