name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bin: # only utils, no build tools, linters, formatter
          - bat
          - bottom
          - delta
          - dust
          - fastfetch
          - fd
          - fzf
          - gh
          - hexyl
          - hyperfine
          - iperf
          - jq
          - lsd
          - lshw
          - neovim
          - pigz
          - pixz
          - rclone
          - ripgrep
          - socat
          - tokei
          - zstd
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y podman skopeo
      - name: login
        run: podman login --username pusnow --password "${{ secrets.CR_PW }}" ghcr.io
      - name: dbuild.sh
        run: ./dbuild.sh ${{ matrix.bin }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DOCKER_PATH: ghcr.io/pusnow/bin
          OS: ${{ matrix.os }}
          GH_EVENT: ${{ github.event_name }}
  pack:
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y podman skopeo
      - name: login
        run: podman login --username pusnow --password "${{ secrets.CR_PW }}" ghcr.io
      - name: dpack.sh
        run: |
          ./dpack.sh \
            bat \
            bottom \
            delta \
            dust \
            fastfetch \
            fd \
            fzf \
            gh \
            hexyl \
            hyperfine \
            iperf \
            jq \
            lsd \
            lshw \
            neovim \
            pigz \
            pixz \
            rclone \
            ripgrep \
            socat \
            tokei \
            zstd

        env:
          GITHUB_TOKEN: ${{ github.token }}
          DOCKER_PATH: ghcr.io/pusnow/bin
          OS: ${{ matrix.os }}
          GH_EVENT: ${{ github.event_name }}

