name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: # only utils, no build tools, linters, formatter
          - bat
          - bottom
          - delta
          - distrobox
          - dnslookup
          - dust
          - fd
          - fzf
          - gh
          - hexyl
          - hyperfine
          - iperf
          - jq
          - lsd
          - lshw
          - neofetch
          - neovim
          - pigz
          - pixz
          - rclone
          - ripgrep
          - socat
          - tokei
          - zstd
        arch:
          - x64
          - aarch64

    steps:
      - uses: actions/checkout@v3
      - name: qemu-user-static
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static
        if: matrix.arch != 'x64'
      - name: login
        run: podman login --username pusnow --password "${{ secrets.CR_PW }}" ghcr.io
      - name: dbuild.sh
        run: ./dbuild.sh ${{ matrix.bin }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DOCKER_PATH: ghcr.io/pusnow/bin
          ARCH: ${{ matrix.arch }}
          GH_EVENT: ${{ github.event_name }}
  pack:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x64
          - aarch64
    steps:
      - uses: actions/checkout@v2
      - name: login
        run: podman login --username pusnow --password "${{ secrets.CR_PW }}" ghcr.io
      - name: dpack.sh
        run: |
          ./dpack.sh \
            bat \
            bottom \
            delta \
            distrobox \
            dnslookup \
            dust \
            fd \
            fzf \
            gh \
            hexyl \
            hyperfine \
            iperf \
            jq \
            lsd \
            lshw \
            neofetch \
            neovim \
            pigz \
            pixz \
            rclone \
            ripgrep \
            socat \
            tokei \
            zstd

        env:
          GITHUB_TOKEN: ${{ github.token }}
          DOCKER_PATH: ghcr.io/pusnow/bin
          ARCH: ${{ matrix.arch }}
          GH_EVENT: ${{ github.event_name }}

  keepalive:
    needs: [pack]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
