name: main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  main:
    strategy:
      matrix:
        bin:
          [
            "micro",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd  ${{ matrix.bin }
          ./build.sh
